// examples/angular/src/app/app.component.ts
import { Component } from '@angular/core'
import MediaInfoFactory from 'mediainfo.js'
import { MediaInfo, ReadChunkFunc, Result } from 'mediainfo.js/dist/types'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})
export class AppComponent {
  videoInfo = 'No file'

  getMetadata(
    mediainfo: MediaInfo,
    fileinput: HTMLInputElement
  ): Promise<string> {
    return new Promise<string>((resolve) => {
      const file = fileinput.files[0]
      if (!file) {
        return resolve("Can't get media information")
      }

      const getSize = () => file.size
      const readChunk: ReadChunkFunc = (chunkSize, offset) =>
        new Promise((resolve, reject) => {
          const reader = new FileReader()
          reader.onload = (event: ProgressEvent<FileReader>) => {
            if (event.target.error) {
              reject(event.target.error)
            }
            resolve(new Uint8Array(event.target.result as ArrayBuffer))
          }
          reader.readAsArrayBuffer(file.slice(offset, offset + chunkSize))
        })
      const p = <Promise<Result>>mediainfo.analyzeData(getSize, readChunk)
      p.then((result: string) => resolve(result)).catch(() =>
        resolve("Can't get media information")
      )
    })
  }

  onChangeFile(input: HTMLInputElement): void {
    MediaInfoFactory({ format: 'text' }, (mediainfo: MediaInfo) => {
      this.getMetadata(mediainfo, input).then((info) => {
        this.videoInfo = info.replace(/(?:\r\n|\r|\n)/g, '<br>')
      })
    })
  }
}

<h1>MediaInfo Angular Example</h1>

<input
  type="file"
  placeholder="Select video..."
  (change)="onChangeFile($event.target)"
/>
<br /><br />
<div [innerHtml]="videoInfo"></div>

// examples/webpack-react/src/App.tsx
import React, { type ChangeEvent, useState, useEffect, useRef } from 'react'
import mediaInfoFactory from 'mediainfo.js'
import type { ReadChunkFunc, MediaInfo } from 'mediainfo.js'

function getMetadata(mi: MediaInfo<'text'>, file: File) {
  const getSize = () => file.size
  const readChunk: ReadChunkFunc = (chunkSize, offset) =>
    new Promise((resolve, reject) => {
      const reader = new FileReader()
      reader.onload = (event: ProgressEvent<FileReader>) => {
        if (event.target?.error) {
          reject(event.target.error)
        }
        resolve(new Uint8Array(event.target?.result as ArrayBuffer))
      }
      reader.readAsArrayBuffer(file.slice(offset, offset + chunkSize))
    })

  return mi.analyzeData(getSize, readChunk)
}

function App() {
  const miRef = useRef<MediaInfo<'text'>>()
  const [result, setResult] = useState('')

  useEffect(() => {
    mediaInfoFactory({ format: 'text' }).then((mi) => {
      miRef.current = mi
    })

    return () => {
      if (miRef.current) {
        miRef.current.close()
      }
    }
  }, [])

  const handleChange = (ev: ChangeEvent<HTMLInputElement>) => {
    const file = ev.target.files?.[0]
    if (file && miRef.current) {
      getMetadata(miRef.current, file).then(setResult)
    }
  }

  return (
    <>
      <input type="file" placeholder="Select file..." onChange={handleChange} />
      <pre>{result}</pre>
    </>
  )
}

export default App
