// examples/angular/src/app/app.component.ts
import { Component } from '@angular/core'

import mediaInfoFactory from 'mediainfo.js'
import type { MediaInfo, ReadChunkFunc } from 'mediainfo.js'

function makeReadChunk(file: File): ReadChunkFunc {
  return async (chunkSize: number, offset: number) =>
    new Uint8Array(await file.slice(offset, offset + chunkSize).arrayBuffer())
}

@Component({
  selector: 'app-root',
  standalone: true,
  templateUrl: './app.component.html',
})
export class AppComponent {
  mediaInfo: MediaInfo<'text'> | undefined = undefined
  result = ''
  disabled = true

  constructor() {
    mediaInfoFactory({ format: 'text' })
      .then((mediaInfo) => {
        this.mediaInfo = mediaInfo
        this.disabled = false
      })
      .catch((error: unknown) => {
        console.error(error)
      })
  }

  onChangeFile(event: Event) {
    if (this.mediaInfo && event.target) {
      const target = event.target as HTMLInputElement
      if (target.files && target.files.length > 0) {
        const file = target.files[0]
        this.mediaInfo
          .analyzeData(file.size, makeReadChunk(file))
          .then((result) => {
            this.result = result
          })
          .catch((error: unknown) => {
            console.error(error)
          })
      }
    }
  }
}

<h1>MediaInfo Angular Example</h1>

<input
  (change)="onChangeFile($event)"
  [disabled]="disabled ? true : null"
  placeholder="Select file..."
  type="file"
/>
<br />
<pre [innerHtml]="result"></pre>

// examples/vite-react/src/App.tsx
import { type ChangeEvent, useState, useEffect, useRef } from 'react'

import mediaInfoFactory from 'mediainfo.js'
import type { MediaInfo, ReadChunkFunc } from 'mediainfo.js'

function makeReadChunk(file: File): ReadChunkFunc {
  return async (chunkSize: number, offset: number) =>
    new Uint8Array(await file.slice(offset, offset + chunkSize).arrayBuffer())
}

function App() {
  const mediaInfoRef = useRef<MediaInfo<'text'> | null>(null)
  const [result, setResult] = useState('')

  useEffect(() => {
    mediaInfoFactory({ format: 'text' })
      .then((mi) => {
        mediaInfoRef.current = mi
      })
      .catch((error: unknown) => {
        console.error(error)
      })

    return () => {
      if (mediaInfoRef.current) {
        mediaInfoRef.current.close()
      }
    }
  }, [])

  const handleChange = (ev: ChangeEvent<HTMLInputElement>) => {
    const file = ev.target.files?.[0]
    if (file && mediaInfoRef.current) {
      mediaInfoRef.current
        .analyzeData(file.size, makeReadChunk(file))
        .then(setResult)
        .catch((error: unknown) => {
          console.error(error)
        })
    }
  }

  return (
    <>
      <input type="file" placeholder="Select file..." onChange={handleChange} />
      <pre>{result}</pre>
    </>
  )
}

export default App
